Repository codestates-seb/seb40_main_034, pull requests merged in 2022-12, with the labels that each got.

#167 Feat:닉네임중복확인 기능을 추가했습니다
  client/src/Api/nicknameCheck.js
  client/src/Pages/Login.jsx
  client/src/Pages/Signup.jsx
Labels: FRONTEND

#170 FEAT: 무한스크롤 구현 및 글 작성 페이지 추가
  client/src/Api/MainApi.js
  client/src/Components/Common/Tab.jsx
  client/src/Components/List/List.jsx
  client/src/Components/Main/ListContainer.jsx
  client/src/Components/Post/Tagform.jsx
  client/src/Hooks/useInput.js
  client/src/Hooks/useTag.js
  client/src/Pages/Main.jsx
  client/src/Pages/Post.jsx
Labels: FRONTEND

#172 Feat:닉네임중복확인버튼 수정/ 로그아웃페이지 생성
  client/src/Pages/Login.jsx
  client/src/Pages/Logout.jsx
  client/src/Pages/Signup.jsx
Labels: FRONTEND

#173 FEAT: 배포 자동화 재설정 및 메인 컴포넌트 파일 구조 조정
  .github/.DS_Store
  .github/workflows/fe_deploy.yml
  client/src/Components/Common/MiniProfile.jsx
  client/src/Components/Layout/AboutBtn.jsx
  client/src/Components/Layout/Footer.jsx
  client/src/Components/Layout/GoUpBtn.jsx
  client/src/Components/Layout/Header.jsx
  client/src/Components/Layout/Sidebar.jsx
  client/src/Components/Layout/Tab.jsx
  client/src/Components/Layout/WriteBtn.jsx
  client/src/Components/Main/List.jsx
  client/src/Components/Main/ListContainer.jsx
  client/src/Pages/Layout.jsx
  client/src/Pages/LayoutH.jsx
  client/src/Pages/LayoutHS.jsx
  client/src/Pages/Main.jsx
  client/src/Pages/Post.jsx
Labels: FRONTEND

#174 Style:로그인/회원가입화면수정
  client/src/Components/Common/Btn.jsx
  client/src/Pages/Login.jsx
  client/src/Pages/Signup.jsx
Labels: FRONTEND

#175 Feat: Map Pagination front side 추가
  client/src/Api/MapApi.js
  client/src/Components/MapPagination/MapPagination.jsx
  client/src/Components/MapPagination/style.jsx
  client/src/Components/MapSide/MapSide.jsx
  client/src/Components/MapSide/style.jsx
  client/src/Components/MapView/MapView.jsx
  client/src/Pages/Map.jsx
Labels: FRONTEND

#177 FIX: 라우터, 레이아웃 수정, post 페이지 수정
  client/src/Components/Common/InputForm.jsx
  client/src/Components/Common/Tag.jsx
  client/src/Components/Layout/Sidebar.jsx
  client/src/Components/Post/Tagform.jsx
  client/src/Hooks/CustomHook.js
  client/src/Hooks/useInput.js
  client/src/Hooks/useTag.js
  client/src/Pages/Layout.jsx
  client/src/Pages/Post.jsx
  client/src/Routes/AppRouter.jsx
Labels: FRONTEND

#178 FIX: 라우터 경로에 있던 오탈자를 수정합니다.
  client/src/Routes/AppRouter.jsx
Labels: FRONTEND

#179 Fix:Map Side Width 수정
  client/src/Components/MapSide/style.jsx
Labels: FRONTEND

#180 FIX: index.html 수정 및 카카오 API 키 (배포용) 등록
  client/public/index.html
Labels: FRONTEND

#182 FIX: 배포 자동화 시 카카오 키도 환경변수에 생성되도록 수정합니다.
  .github/workflows/fe_deploy.yml
Labels: FRONTEND

#184 FEAT: Custon Alert 적용
  client/package-lock.json
  client/package.json
  client/src/Components/Common/Btn.jsx
  client/src/Pages/Login.jsx
  client/src/Pages/Post.jsx
  client/src/Utils/customAlert.js
  client/src/initializer.css
Labels: FRONTEND

#187 FIX: 배포 자동화가 제대로 진행되지 않는 문제 수정
  .github/workflows/fe_deploy.yml
Labels: FRONTEND

#188 FEAT: gpsY값을 location 자리에 사용하도록 수정
  client/src/Components/Main/List.jsx
  client/src/Components/Main/ListContainer.jsx
Labels: FRONTEND

#189 Style:SignupAlertEdit
  client/src/Pages/Login.jsx
  client/src/Pages/Signup.jsx
  client/src/Utils/customAlert.js
Labels: FRONTEND

#190 FIX: 배포 자동화 yml의 오탈자를 수정합니다.
  .github/workflows/fe_deploy.yml
Labels: FRONTEND

#191 FIX: 헤더 수정 및 주소 검색 로직 추가
  client/src/Api/MainApi.js
  client/src/Api/PostApi.js
  client/src/Components/Common/InputForm.jsx
  client/src/Components/Layout/Header.jsx
  client/src/Components/Layout/Tab.jsx
Labels: FRONTEND

#192 Feat:onBlurEvent
  client/src/Pages/Login.jsx
  client/src/Pages/Signup.jsx
Labels: FRONTEND

#193 FEAT: 글쓰기 페이지에 장소 검색 기능이 추가됩니다.
  client/src/Api/PostApi.js
  client/src/Components/Post/PlaceSearchModal.jsx
  client/src/Pages/LayoutHS.jsx
  client/src/Pages/Main.jsx
  client/src/Pages/Post.jsx
Labels: FRONTEND

#194 FIX: 배포 자동화 환경변수에 카카오 API 키를 추가합니다.
  .github/workflows/fe_deploy.yml
Labels: FRONTEND

#195 DESIGN: 로딩 컴포넌트 변경
  client/src/Assets/img/loading.svg
  client/src/Components/Main/List.jsx
  client/src/Components/Main/ListContainer.jsx
  client/src/Pages/Loading.jsx
  client/src/Pages/Post.jsx
Labels: FRONTEND

#196 Fix: Map props 변경, Review 기본 profileImg 설정, Input 변경
  client/src/Components/EditDetail/EditDetail.jsx
  client/src/Components/EditDetail/style.jsx
  client/src/Components/MapPagination/style.jsx
  client/src/Components/MapSide/MapSide.jsx
  client/src/Pages/Map.jsx
Labels: FRONTEND

#197 Fix:Mypage, MypageEdit 기본 profileImg 설정
  client/src/Components/EditDetail/EditDetail.jsx
  client/src/Components/MyPage/MyInfo/MyInfo.jsx
Labels: FRONTEND

#198 [FIX] Authorization response header 리턴
  server/src/main/java/com/example/seb_main_project/member/dto/AuthDto.java
  server/src/main/java/com/example/seb_main_project/security/controller/SecurityController.java
  server/src/main/java/com/example/seb_main_project/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/example/seb_main_project/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/example/seb_main_project/security/jwt/JwtTokenizer.java
  server/src/main/java/com/example/seb_main_project/security/repository/RefreshTokenRepository.java
  server/src/main/java/com/example/seb_main_project/security/service/AuthService.java
Labels: BACKEND

#199 FEAT: 로그인된 유저 정보를 STORE에서 일부 가져오도록 변경
  client/src/Components/Common/InputForm.jsx
  client/src/Components/Common/MiniProfile.jsx
  client/src/Components/Layout/Header.jsx
  client/src/Components/Layout/Sidebar.jsx
  client/src/Components/Layout/Tab.jsx
  client/src/Components/Main/List.jsx
  client/src/Pages/LayoutHS.jsx
  client/src/Pages/Post.jsx
  client/src/Routes/AppRouter.jsx
Labels: FRONTEND

#200 [FIX] 로그인 시에 두 토큰을 res.body 리턴
  server/src/main/java/com/example/seb_main_project/member/dto/AuthDto.java
  server/src/main/java/com/example/seb_main_project/security/filter/JwtAuthenticationFilter.java
Labels: BACKEND

#201 FEAT: 요청 헤더에 토큰을 포함한 인스턴스 생성 및 postApi 수정
  client/src/Api/PostApi.js
  client/src/Api/tokenroot.js
Labels: FRONTEND

#202 Feat:로그인페이지에useEffect추가
  client/src/Pages/Login.jsx
  client/src/Store/Auth.js
  client/src/Store/Headerauth.js
  client/src/Store/index.js
Labels: FRONTEND

#203 FIX: tokenroot BEARER 문자열 추가
  client/src/Api/tokenroot.js
Labels: FRONTEND

#204 Feat:로그인페이지 수정
  client/src/Api/Valid.js
  client/src/Pages/Login.jsx
  client/src/Store/Headerauth.js
  client/src/Store/index.js
Labels: FRONTEND

#205 FEAT: API 수정 및 redirect 정상화
  client/src/Api/PostApi.js
  client/src/Api/tokenroot.js
  client/src/Pages/Post.jsx
Labels: FRONTEND

#208 [FEAT] 게시글 전체 조회 시, 접속한 유저가 북마크한 게시글 확인 가능
  server/src/main/java/com/example/seb_main_project/post/controller/PostController.java
  server/src/main/java/com/example/seb_main_project/post/dto/PostDto.java
  server/src/main/java/com/example/seb_main_project/post/entity/Post.java
  server/src/main/java/com/example/seb_main_project/post/mapper/PostMapper.java
  server/src/main/java/com/example/seb_main_project/post/service/PostService.java
  server/src/main/java/com/example/seb_main_project/response/MultiResponseDto.java
Labels: BACKEND

#209 [FEAT] 북마크 시 response 추가
  server/src/main/java/com/example/seb_main_project/bookmark/controller/BookmarkController.java
Labels: BACKEND

#210 FEAT: 북마크, 무한스크롤 로직 개선
  client/package-lock.json
  client/package.json
  client/src/Api/MainApi.js
  client/src/Components/Main/List.jsx
  client/src/Components/Main/ListContainer.jsx
  client/src/Pages/Post.jsx
  client/src/Utils/grammarCheck.js
Labels: FRONTEND

#214 Fix: Edit navi 경로수정
  client/src/Components/MyPage/MyInfo/MyInfo.jsx
Labels: FRONTEND

#216 Feat:SignupPageRedirection
  client/src/Pages/Signup.jsx
Labels: FRONTEND

#218 Delete fe_deploy.yml
  .github/workflows/fe_deploy.yml
Labels: FRONTEND

#220 Feat/article detail response
  server/src/main/java/com/example/seb_main_project/post/dto/PostDto.java
  server/src/main/java/com/example/seb_main_project/post/mapper/PostMapper.java
  server/src/main/java/com/example/seb_main_project/security/controller/SecurityController.java
  server/src/main/java/com/example/seb_main_project/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/example/seb_main_project/security/filter/JwtVerificationFilter.java
Labels: BACKEND

#221 Fix: Mypage Edit api 요청 수정
  client/src/Api/MyinfoApi.js
  client/src/Components/EditDetail/EditDetail.jsx
Labels: FRONTEND

#222 Feat닉네임수정시중복확인버튼추가
  client/src/Components/EditDetail/EditDetail.jsx
  client/src/Pages/Login.jsx
  client/src/Pages/Signup.jsx
Labels: FRONTEND

#223 Feat:회원가입서버변경
  client/src/Components/EditDetail/EditDetail.jsx
  client/src/Pages/Signup.jsx
Labels: FRONTEND

#225 Feat:Edit페이지Alert변경
  client/src/Components/EditDetail/EditDetail.jsx
Labels: FRONTEND

#224 Feat/detail ver2
  client/src/Api/DetailApi.js
  client/src/Components/Detail/CommentList.jsx
  client/src/Pages/Detail.jsx
Labels: FRONTEND

#232 Feat/post like update
  .github/workflows/fe_deploy.yml
  server/src/main/java/com/example/seb_main_project/member/entity/Member.java
  server/src/main/java/com/example/seb_main_project/post/dto/PostDto.java
  server/src/main/java/com/example/seb_main_project/post/entity/Post.java
  server/src/main/java/com/example/seb_main_project/post/mapper/PostMapper.java
  server/src/main/java/com/example/seb_main_project/postlike/controller/PostLikeController.java
  server/src/main/java/com/example/seb_main_project/postlike/dto/PostLikeDto.java
  server/src/main/java/com/example/seb_main_project/postlike/dto/PostLikeResponseDto.java
  server/src/main/java/com/example/seb_main_project/postlike/entity/PostLike.java
  server/src/main/java/com/example/seb_main_project/postlike/mapper/PostLikeMapper.java
  server/src/main/java/com/example/seb_main_project/postlike/repository/PostLikeRepository.java
  server/src/main/java/com/example/seb_main_project/postlike/service/PostLikeService.java
Labels: BACKEND

#234 Feat:writeBtn위치변경
  client/src/Components/Layout/AboutBtn.jsx
  client/src/Components/Layout/WriteBtn.jsx
Labels: FRONTEND

#237 FEAT: 배포 자동화 재개시
  .github/fe_deploy.yml
Labels: FRONTEND

#238 FIX: 메인 화면과 글 작성 시 이미지가 정상적으로 표시됩니다
  client/src/Api/HeaderApi.js
  client/src/Components/Common/Tag.jsx
  client/src/Components/Main/List.jsx
  client/src/Components/Main/ListContainer.jsx
  client/src/Components/Post/Tagform.jsx
  client/src/Pages/Post.jsx
Labels: FRONTEND

#239 FIX: 배포 자동화 재개시
  .github/workflows/fe_deploy.yml
Labels: FRONTEND

#244 Feat:글상세페이지 수정
  client/src/Pages/Map.jsx
Labels: FRONTEND

#245 [FEAT] 게시글 조회 시 프로필 이미지 조회
  server/src/main/java/com/example/seb_main_project/post/dto/PostDto.java
  server/src/main/java/com/example/seb_main_project/post/mapper/PostMapper.java
Labels: BACKEND

#246 Feat:LoadingPageEdit
  client/src/Components/Main/ListContainer.jsx
  client/src/Pages/Loading.jsx
Labels: FRONTEND

#247 FIX: 로딩 컴포넌트 사이즈 조정 및 조건부 렌더링 수정
  client/src/Components/Main/ListContainer.jsx
  client/src/Pages/Loading.jsx
Labels: FRONTEND

#249 FIX: 헤더 정보를 redux state가 아닌 api에서 받아오도록 변경
  client/src/Api/HeaderApi.js
  client/src/Components/Layout/Tab.jsx
  client/src/Components/Main/List.jsx
  client/src/Components/Main/ListContainer.jsx
Labels: FRONTEND

#251 Feat:기본맵주소변경
  client/src/Components/Layout/Tab.jsx
Labels: FRONTEND

#252 Fix: Edit reload 오류 수정
  client/src/Components/EditDetail/EditDetail.jsx
Labels: FRONTEND

#253 Feat:Mapside
  client/src/Api/MapApi.js
  client/src/Components/MapSide/MapSide.jsx
Labels: FRONTEND

#254 FIX: 태그가 메인에서도 뿌려짐, 글 작성시 태그 선택하면 나머지 태그 사라짐
  .github/fe_deploy.yml
  client/src/Components/Common/Tag.jsx
  client/src/Components/Main/List.jsx
  client/src/Components/Main/ListContainer.jsx
  client/src/Components/Post/Tagform.jsx
  client/src/Pages/Post.jsx
Labels: FRONTEND

#255 Fix: 공백 ID 요청 수정
  client/src/Components/EditDetail/EditDetail.jsx
  client/src/Components/MyPage/MyInfo/MyInfo.jsx
Labels: FRONTEND

#257 console창 제거
  client/src/Components/EditDetail/EditDetail.jsx
  client/src/Components/Main/ListContainer.jsx
  client/src/Components/MapPagination/MapPagination.jsx
  client/src/Components/MapSide/MapSide.jsx
  client/src/Components/MyPage/FollowModal/FollowModal.jsx
  client/src/Components/MyPage/MyInfo/MyInfo.jsx
  client/src/Pages/Detail.jsx
  client/src/Pages/Login.jsx
  client/src/Pages/Post.jsx
  client/src/Pages/Signup.jsx
Labels: FRONTEND

#260 Delete .github/workflows directory
  .github/workflows/fe_deploy.yml
Labels: FRONTEND

#261 Create README.md
  README.md
Labels: COMMON

#262 Update README.md
  README.md
Labels: COMMON

#263 Update README.md
  README.md
Labels: COMMON

#265 Frontend 릴리즈
  client/src/Api/DetailApi.js
  client/src/Components/Detail/DetailModal.jsx
  client/src/Components/Post/PlaceSearchModal.jsx
  client/src/Components/Post/Tagform.jsx
  client/src/Pages/Detail.jsx
  client/src/Pages/Post.jsx
Labels: FRONTEND

#266 Feat: Bookmark 추가
  client/src/Api/MyinfoApi.js
  client/src/Components/EditDetail/EditDetail.jsx
  client/src/Components/MyPage/MyInfo/MyInfo.jsx
  client/src/Components/MyPage/MyList/MyList.jsx
  client/src/Components/MyPage/Mybookmark/MyBookmark.jsx
  client/src/Components/MyPage/Mybookmark/style.jsx
Labels: FRONTEND

#267 [FEAT] 로그인 및 사용자 확인 로직 개선
  server/src/main/java/com/example/seb_main_project/post/controller/PostController.java
  server/src/main/java/com/example/seb_main_project/security/config/SecurityConfig.java
  server/src/main/java/com/example/seb_main_project/security/filter/JwtVerificationFilter.java
Labels: BACKEND

#270 Fix: Imgur api 배포페이지 테스트용
  client/src/Components/EditDetail/EditDetail.jsx
Labels: FRONTEND

#271 Fix: 주소 / 오류로 url 임시 변경
  client/src/Components/EditDetail/EditDetail.jsx
  client/src/Pages/Login.jsx
  client/src/Pages/Signup.jsx
Labels: FRONTEND

#272 Fix: url 변경해도 동일 오류 발생하여 원상복귀
  client/src/Components/EditDetail/EditDetail.jsx
  client/src/Pages/Login.jsx
  client/src/Pages/Signup.jsx
Labels: FRONTEND

#273 Fix:Imgur api 요청 테스트
  client/src/Components/EditDetail/EditDetail.jsx
  client/src/Pages/ImgurTest.jsx
  client/src/Routes/AppRouter.jsx
Labels: FRONTEND

#274 Fix: 배포페이지 imgur 테스트
  client/src/Components/EditDetail/EditDetail.jsx
  client/src/Pages/Signup.jsx
Labels: FRONTEND

#275 Fix: Imgur ID 테스트용
  client/src/Api/HeaderApi.js
  client/src/Components/EditDetail/EditDetail.jsx
  client/src/Components/Layout/Tab.jsx
Labels: FRONTEND

#276 Fix: imgur id 오타 수정
  client/src/Components/EditDetail/EditDetail.jsx
Labels: FRONTEND

#277 Fix: Edit imgur token 수정
  client/src/Components/EditDetail/EditDetail.jsx
  client/src/Pages/ImgurTest.jsx
Labels: FRONTEND

#278 Fix: imgur 요청 오타 수정
  client/src/Components/EditDetail/EditDetail.jsx
Labels: FRONTEND

#279 Feat/follow
  server/scripts/initialize.sh
  server/scripts/server_clear.sh
  server/scripts/server_start.sh
  server/scripts/server_stop.sh
  server/src/main/java/com/example/seb_main_project/exception/ExceptionCode.java
  server/src/main/java/com/example/seb_main_project/follow/controller/FollowController.java
  server/src/main/java/com/example/seb_main_project/follow/controller/FollowService.java
  server/src/main/java/com/example/seb_main_project/follow/dto/FollowDto.java
  server/src/main/java/com/example/seb_main_project/follow/entity/Follow.java
  server/src/main/java/com/example/seb_main_project/follow/mapper/FollowMapper.java
  server/src/main/java/com/example/seb_main_project/follow/repository/FollowRepository.java
  server/src/main/java/com/example/seb_main_project/member/entity/Member.java
Labels: BACKEND

#280 [FEAT] 게시글에 대해 address, subAddress 필드 추가
  server/src/main/java/com/example/seb_main_project/bookmark/dto/BookmarkDto.java
  server/src/main/java/com/example/seb_main_project/bookmark/mapper/BookmarkMapper.java
  server/src/main/java/com/example/seb_main_project/post/dto/PostDto.java
  server/src/main/java/com/example/seb_main_project/post/entity/Post.java
  server/src/main/java/com/example/seb_main_project/post/mapper/PostMapper.java
  server/src/main/java/com/example/seb_main_project/post/service/PostService.java
Labels: BACKEND

#284 Feat: LandingPage
  client/package-lock.json
  client/package.json
  client/src/Pages/Landingpage.jsx
  client/src/Routes/AppRouter.jsx
Labels: FRONTEND
